"""add transaction model

Revision ID: bd16f44a3938
Revises: 8735482b1448
Create Date: 2025-07-27 21:38:26.274319

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd16f44a3938"
down_revision: Union[str, Sequence[str], None] = "8735482b1448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index("idx_transactions_customer_product", "transactions", ["customer_id", "product_id"], unique=False)
    op.create_index(op.f("ix_transactions_currency"), "transactions", ["currency"], unique=False)
    op.create_index(op.f("ix_transactions_customer_id"), "transactions", ["customer_id"], unique=False)
    op.create_index(op.f("ix_transactions_product_id"), "transactions", ["product_id"], unique=False)
    op.create_index(op.f("ix_transactions_timestamp"), "transactions", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_timestamp"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_product_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_customer_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_currency"), table_name="transactions")
    op.drop_index("idx_transactions_customer_product", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
