name: Python application

on:
  push:
    branches: [ "feat-cicd" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude alembic,tests
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create .env file and export env variables
      run: |
        echo "${{ secrets.ENV_CONTENT }}" > .env
        while IFS='=' read -r key value; do
          echo "$key=$value" >> $GITHUB_ENV
        done < .env
    - name: Test with pytest
      run: |
        python3 -m pytest
